spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistreams
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect